DROP TABLE IF EXISTS round_payments CASCADE;
DROP TABLE IF EXISTS payment_transactions CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS mature_mining_reward_checkpoints CASCADE;
DROP TABLE IF EXISTS mature_mining_rewards CASCADE;
DROP TABLE IF EXISTS immature_mining_rewards CASCADE;
DROP TABLE IF EXISTS token_events CASCADE;
DROP TABLE IF EXISTS watcher_blocks CASCADE;
DROP TABLE IF EXISTS mining_rounds CASCADE;
DROP TABLE IF EXISTS watchers CASCADE;

